In [1]:
#boolean indexing
import numpy as np
a = np.arange(25).reshape(5,5)
a[a > 12] = 5
a[a == 5] = -1
print(a)
print(a == -1)

[[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
[[False False False False False]
 [ True False False False False]
 [False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [2]:
#boolean with 2 tests
a = np.arange(25).reshape(5,5)
b = np.arange(25).reshape(5,5)
a[np.logical_or(a<1,a>16)] = 0.0
b[np.logical_and(a>9,a<19)] = 0.0
print(a)
print(b)
a > 4

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [ 0  0 17 18 19]
 [20 21 22 23 24]]


array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False]])

In [3]:
#avoid loops
g = 20
h = 80
smin = tmin = 5.0
smax = tmax = 10.0
s = np.linspace(smin, smax, g, endpoint=True)
t = np.linspace(tmin, tmax, h, endpoint=False)
print(s.shape)
print(t.shape)
print(s)
t

(20,)
(80,)
[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


array([5.    , 5.0625, 5.125 , 5.1875, 5.25  , 5.3125, 5.375 , 5.4375,
       5.5   , 5.5625, 5.625 , 5.6875, 5.75  , 5.8125, 5.875 , 5.9375,
       6.    , 6.0625, 6.125 , 6.1875, 6.25  , 6.3125, 6.375 , 6.4375,
       6.5   , 6.5625, 6.625 , 6.6875, 6.75  , 6.8125, 6.875 , 6.9375,
       7.    , 7.0625, 7.125 , 7.1875, 7.25  , 7.3125, 7.375 , 7.4375,
       7.5   , 7.5625, 7.625 , 7.6875, 7.75  , 7.8125, 7.875 , 7.9375,
       8.    , 8.0625, 8.125 , 8.1875, 8.25  , 8.3125, 8.375 , 8.4375,
       8.5   , 8.5625, 8.625 , 8.6875, 8.75  , 8.8125, 8.875 , 8.9375,
       9.    , 9.0625, 9.125 , 9.1875, 9.25  , 9.3125, 9.375 , 9.4375,
       9.5   , 9.5625, 9.625 , 9.6875, 9.75  , 9.8125, 9.875 , 9.9375])

In [5]:
#time elapsed
import time
import numpy as np
a = 10
b = 50
c = np.linspace(1.0, 3.0, a, endpoint=True)
d = np.linspace(0.0, 4.0, b, endpoint=False)
T0 = time.time()
f = np.zeros((a, b))
for i in range(a):
    for j in range(b):
        f[i,j] = np.sin(2.0*np.pi*c[i]*d[j])
T1 = time.time()
print("time elapsed: {} s".format(T1-T0))
print(c)
d

time elapsed: 0.0014615058898925781 s
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


array([0.  , 0.08, 0.16, 0.24, 0.32, 0.4 , 0.48, 0.56, 0.64, 0.72, 0.8 ,
       0.88, 0.96, 1.04, 1.12, 1.2 , 1.28, 1.36, 1.44, 1.52, 1.6 , 1.68,
       1.76, 1.84, 1.92, 2.  , 2.08, 2.16, 2.24, 2.32, 2.4 , 2.48, 2.56,
       2.64, 2.72, 2.8 , 2.88, 2.96, 3.04, 3.12, 3.2 , 3.28, 3.36, 3.44,
       3.52, 3.6 , 3.68, 3.76, 3.84, 3.92])

In [6]:
#using array
cd, dd = np.meshgrid(c, d, indexing="ij")
print(cd[:,4])
print(dd[5,:])
t = time.time()
g2 = np.sin(2.0*np.pi*cd*dd)
t0 = time.time()
print("time elapsed: {} s".format(t0-t))

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]
[0.   0.08 0.16 0.24 0.32 0.4  0.48 0.56 0.64 0.72 0.8  0.88 0.96 1.04
 1.12 1.2  1.28 1.36 1.44 1.52 1.6  1.68 1.76 1.84 1.92 2.   2.08 2.16
 2.24 2.32 2.4  2.48 2.56 2.64 2.72 2.8  2.88 2.96 3.04 3.12 3.2  3.28
 3.36 3.44 3.52 3.6  3.68 3.76 3.84 3.92]
time elapsed: 0.00012922286987304688 s


In [7]:
#concantinate
a = np.array([0, 1, 6, 4])
b = np.array([1, 7, 5, 8])
c = np.array([5, 2, 3])
print(np.concatenate([a,b,c]))
g = np.array([[1, 2],
             [4, 5]])
np.concatenate([g,g],axis=1)

[0 1 6 4 1 7 5 8 5 2 3]


array([[1, 2, 1, 2],
       [4, 5, 4, 5]])

In [8]:
#splitting of array
a = [1, 4, 3, 8, 7, 6 ,2, 1]
a1, a2, a3 = np.split(a, [2,4])
print(a1, a2, a3)
b = np.arange(15).reshape(3,5)
left, right = np.hsplit(b, [3])
print(b)
print(left)
print(right)

[1 4] [3 8] [7 6 2 1]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
[[ 3  4]
 [ 8  9]
 [13 14]]


In [9]:
#aggregate
x = np.arange(1, 10)
print(x)
print(np.add.reduce(x))
print(np.multiply.reduce(x))
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[1 2 3 4 5 6 7 8 9]
45
362880
[ 1  3  6 10 15 21 28 36 45]
[     1      2      6     24    120    720   5040  40320 362880]
