In [1]:
#create an array
import numpy as np
a = np.arange(25)
b = np.arange(30)
c = np.arange(27).reshape(3,9)
print(a)
print(b)
c

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [2]:
#meta data of an array
print(c.ndim)
print(c.shape)
print(c.size)
print(c.itemsize)
c.dtype

2
(3, 9)
27
8


dtype('int64')

In [3]:
#array from list
d = np.array([5,10,15,20,25,30])
print(type(d))
print(d.size)
print(d.ndim)
print(d.itemsize)
d.shape

<class 'numpy.ndarray'>
6
1
8


(6,)

In [5]:
#eye,linespace,logspace functions
x = np.eye(5)
dtype = np.float64
y = np.linspace(1,5,10,endpoint=True)
z = np.logspace(1,5,10,endpoint=False,base=10)
print(dtype)
print(x)
print(y)
z

<class 'numpy.float64'>
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


array([1.00000000e+01, 2.51188643e+01, 6.30957344e+01, 1.58489319e+02,
       3.98107171e+02, 1.00000000e+03, 2.51188643e+03, 6.30957344e+03,
       1.58489319e+04, 3.98107171e+04])

In [6]:
#lambda function,array operation
v = np.fromfunction(lambda a,b:a==b,(4,4),dtype=float)
u = np.arange(15).reshape(3,5)
print(v)
print(u)
print(u+u)
print(u*2)
print(u*u)
#matrix multiplication
z = u.transpose()
print(u@z)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


In [7]:
#axis operation and extreme functions
e = np.array([1,2,4,5,3,8,9,7,5,6,11,12]).reshape(3,4)
print(e)
print(e.sum(axis=0))
print(e.sum(axis=1))
print(e.min(),e.max())
print(e.sum())

[[ 1  2  4  5]
 [ 3  8  9  7]
 [ 5  6 11 12]]
[ 9 16 24 24]
[12 27 34]
1 12
73


In [8]:
#universal functions
s = e*np.pi/6.0
print(s)
t = np.tan(s)
print(t)
q = t-s
q

[[0.52359878 1.04719755 2.0943951  2.61799388]
 [1.57079633 4.1887902  4.71238898 3.66519143]
 [2.61799388 3.14159265 5.75958653 6.28318531]]
[[ 5.77350269e-01  1.73205081e+00 -1.73205081e+00 -5.77350269e-01]
 [ 1.63312394e+16  1.73205081e+00  5.44374645e+15  5.77350269e-01]
 [-5.77350269e-01 -1.22464680e-16 -5.77350269e-01 -2.44929360e-16]]


array([[ 5.37514936e-02,  6.84853256e-01, -3.82644591e+00,
        -3.19534415e+00],
       [ 1.63312394e+16, -2.45673940e+00,  5.44374645e+15,
        -3.08784116e+00],
       [-3.19534415e+00, -3.14159265e+00, -6.33693680e+00,
        -6.28318531e+00]])

In [9]:
#multidimensional array
ma = np.arange(50).reshape(5,10)
print(ma)
print(ma[3,2])
print(ma[3:])
print(ma[:,1:3])
print(ma[1:5,:])
m = ma.flatten()
print(m)
for i in m:
    print(i)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
32
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 1  2]
 [11 12]
 [21 22]
 [31 32]
 [41 42]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [10]:
#copying arrays, referencing
rr = np.arange(6)
print(rr)
sky = rr
print(sky)
print(rr is sky)
sky.shape = (3,2)
print(sky)
rr.shape

[0 1 2 3 4 5]
[0 1 2 3 4 5]
True
[[0 1]
 [2 3]
 [4 5]]


(3, 2)

In [11]:
#shallow copying
ra = np.arange(15).reshape(3,5)
print(ra)
hu= ra[:]
print(hu)
print(hu is ra)
hu.shape = (5,3)
print(hu)
ra.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
False
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


(3, 5)

In [12]:
#Checking arrays
print(hu is rr)
print(hu.base is rr)
print(hu.flags.owndata)
print(rr.flags.owndata)

False
False
False
True


In [13]:
#Deep copy
ar = rr.copy()
ar[:] = 0.0
print(rr)
ar

[[0 1]
 [2 3]
 [4 5]]


array([[0, 0],
       [0, 0],
       [0, 0]])